const allNotes = [
  {
    note: "C",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 0,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 1,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 2,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 3,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 4,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 5,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 6,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 7,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "C",
    hasAccidental: true,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "D",
    hasAccidental: true,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "E",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "F",
    hasAccidental: true,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "G",
    hasAccidental: true,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "A",
    hasAccidental: true,
    octave: 8,
    selected: false,
    highlighted: false,
  },
  {
    note: "B",
    hasAccidental: false,
    octave: 8,
    selected: false,
    highlighted: false,
  },
];

export function getFretsWithNotes(tuning) {
  let fretsWithNotes = [];
  let noteIndexes = [];

  for (let tuningNote of tuning) {
    let noteIndex = allNotes.findIndex(
      (note) =>
        note.note === tuningNote.note &&
        note.octave === tuningNote.octave &&
        note.hasAccidental === tuningNote.hasAccidental
    );
    noteIndexes.push(noteIndex);
  }

  for (let i = 0; i < 25; i++) {
    let notesForFret = [];
    for (let noteIndex of noteIndexes) {
      notesForFret.push(allNotes[noteIndex + i]);
    }
    fretsWithNotes.push(notesForFret);
  }

  return fretsWithNotes;
}

// function getPianoNotes(lowestNote, highestNote) {}

// let startNoteIndex = allNotes.findIndex(
//   (note) =>
//     note.note === string.root &&
//     note.octave === string.octave &&
//     note.hasAccidental === string.hasAccidental
// );
// return allNotes.slice(startNoteIndex, startNoteIndex + 25);
